language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - mysql -e 'create database app_testdb'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/codecept run